//aqui añadimos todas las dependencias de la aplicacion
enyo.depends(
	"$lib/layout",
	"$lib/onyx",
	"$lib/thirdparty/taffy-min.js",
	"../assets/css/app.css",
	"common",
	"Cabecera.js",
	"servicioWeb.js",
	"Footer.js",
	"Header.js",
	"Entidades.js",
	"Lista.js",
	"Lugares.js",
	"Edificios.js",
	"ListaEdificios.js",
	"Mapa.js",
	"Mupos.js"
);